### ISSUE TITLE
Latin and Cyrillic glyphs in Step Bold have a different x-height

### ISSUE THREAD

**Issue by StefanPeev** [dbenjaminmiller/step#3]
Latin and Cyrillic glyphs in Step Bold have a different x-height and a different shape for equal glyphs like Latin and Cyrillic **A**, **a**.
The shape and the construction of Latin and Cyrillic glyphs (which are alike - for example **a**, **e**, **o**) are also different in Step Regular.

**Comment by dbenjaminmiller** [comment]
This is because the Cyrillic alphabet is from URW Nimbus Roman. (The Latin corresponds in size to Nimbus', I believe, so it seems to be an intentional design choice, then.) Myself, I only understand languages using Latin and Greek and not Cyrillic, so I'm not comfortable redesigning the characters myself. There are also the Cyrillic characters from STIX to consider: what do you think of those in comparison?

**Comment by dbenjaminmiller** [comment]
Solved in 2.0.4.
